brew install wget

mkdir build
cd build

if [ -n "${RUNTIMENAME}" ]
then
    NODEJS_NAME_PARAM="-DNODEJS_NAME=${RUNTIMENAME}"
else
    NODEJS_NAME_PARAM=""
fi

if [ -n "${RUNTIMEURL}" ]
then
    NODEJS_URL_PARAM="-DNODEJS_URL=${RUNTIMEURL}"
else
    NODEJS_URL_PARAM=""
fi

if [ -n "${RUNTIMEVERSION}" ]
then
    NODEJS_VERSION_PARAM="-DNODEJS_VERSION=${RUNTIMEVERSION}"
else
    NODEJS_VERSION_PARAM=""
fi

if [ -n "${ARCHITECTURE}" ]
then
    CMAKE_OSX_ARCHITECTURES_PARAM="-DCMAKE_OSX_ARCHITECTURES=${ARCHITECTURE}"
else
    CMAKE_OSX_ARCHITECTURES_PARAM=""
fi

# Configure
cmake .. \
-DCMAKE_OSX_DEPLOYMENT_TARGET=10.15 \
-DCMAKE_BUILD_TYPE=RelWithDebInfo \
-DCMAKE_INSTALL_PREFIX=${DISTRIBUTEDIRECTORY}/node-window-rendering \
${NODEJS_NAME_PARAM} \
${NODEJS_URL_PARAM} \
${NODEJS_VERSION_PARAM} \
${CMAKE_OSX_ARCHITECTURES_PARAM}

cd ..

# Build
cmake --build build --target install --config RelWithDebInfo
